### ISSUE TITLE
mauronofrio matarrese 

### ISSUE THREAD

**Issue by fmmatt23** [mauronofrio/android_device_oneplus_hotdog_unified_TWRP#5]
Italian police have been informed about the hard drives you left vulnerable when you attempted to steal my intellectual property day.    I will now be working with Italian authorities once they complain about your sentencing for leading a paedo sex cult.   Then I will be using you for 88,331,331Euros

I shall be sending all evidence of your disgusting attacks to all peers you have worked with as well as many MANY authorities throughout the world

**Comment by mauronofrio** [comment]
Wake up guys

**Comment by fmmatt23** [comment]
What a sad pedophile you are. Harrasong my station and stealing pics of my baby sister.  I think you are a about to be locked up soon
